Discuss selection of client identifiers
intarchboard/draft-iab-privacy-partitioning pull request #70
Opened 2023-12-07 18:59 UTC by tfpauly

Closes #65

2023-12-11 16:05 UTC, mirjak commented on draft-iab-privacy-partitioning.md
> +the value of partitioning.
```suggestion
the value of partitioning. Usually each context uses some kind of identifier which may are may not be directly
associated with a client identity, e.g. a pseudonym or random one-time identifier could be used as well.
```

2023-12-11 16:07 UTC, mirjak requested changes
I proposed one addition to clarify that each context has some kind of identifier. But otherwise this looks fine.

2023-12-11 16:42 UTC, tfpauly commented on draft-iab-privacy-partitioning.md
> +the value of partitioning.
```suggestion
the value of partitioning. Generally, each context involves some form of client identifier,
which might be directly associated with a client identity, but can also be a pseudonym
or a random one-time identifier.
```

2023-12-13 15:11 UTC, chris-wood approved these changes
Lovely!

2023-12-13 15:11 UTC, chris-wood commented on draft-iab-privacy-partitioning.md
> +what servers are being accessed), the overall effect of unlinkability is diminished.
```suggestion
what servers are being accessed), the overall effect of partitioning is diminished.
```

2023-12-13 15:16 UTC, merged